### PR TITLE
Tidy up Get-OpenADGroupMember

### PR DESCRIPTION
**Pull request by jborean93**
Tidies up Get-OpenADGroupMember so it shared code with the common GetOpenADOperation base class. Expands on the documentation a bit and adds a few more tests.

### CODE REVIEW

**Comment by jborean93** [comment]
This is a continuation on https://github.com/jborean93/PSOpenAD/pull/54, I didn't wish to hold up the original author due to my tardiness of the review. The overall functionality is still the same, just more code is now shared with the base class.

**Comment by jborean93** [comment]
@theaquamarine if you get time it would be great if you could expand on the `primaryGroupId` filter that is added https://github.com/jborean93/PSOpenAD/pull/55/files#diff-2cfcb0d22b89d6599568f05862f2de3890c5d9486de080eb468a766e4061b313R68. There's a test talking about `Domain Controllers` but when checking my local AD test instance I see it's a member of that group anyway. I just want figure out why it's being done really.

**Comment by theaquamarine** [comment]
Sure, and sorry, I could've been much clearer there. I'll add a PR to put the important bits of this into comments when I have a chance.
- Since objects don't include their primary groups in their `memberOf` attribute and vice-versa (https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-ada2/cc24555b-61c7-49a2-9748-167b8ce5a512 and https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-samr/0fa91bfb-3199-4b45-99fb-18ac836fc444), the basic "objects with this group in their `memberOf`" query doesn't show find objects with the group as their primary group. This is where Domain Controllers comes in: as it's the primary group for all DCs, no members would be listed if we only looked at DC's `memberOf`.
- Instead primary groups are recorded as the group RID in the object's `primaryGroupID` attribute, so we get the group's RID ([updated in main to get it from `primaryGroupToken`](https://github.com/jborean93/PSOpenAD/blob/3ae3f310b1a83874f645a178ee81e31641d221ba/src/Commands/OpenADGroupMember.cs#L58-L61)) then [change the LDAP query we're using to find members of the groups to also return objects with `primaryGroupID` set to that RID](https://github.com/jborean93/PSOpenAD/blob/3ae3f310b1a83874f645a178ee81e31641d221ba/src/Commands/OpenADGroupMember.cs#L65-L68). Thinking on it, this should probably strictly be checking the object's domain is also the same as the group's.
- The test is ensuring that requesting the members of Domain Controllers returns something, with Domain Controllers chosen as of the groups used as primary groups by default (Domain Controllers, Domain Computers, and Domain Users, off the top of my head), it's the least likely to have had objects added in a way that it shows up on their `memberOf`.

**Comment by jborean93** [comment]
Thanks for the information, makes a bit more sense. Happy to see any further PRs from yourself, thanks for implementing this as well!

**Pull request merged**
